class LocalizationPun {
  static const Map<String, String> translations = {
    'cattles': 'ਪਸ਼ੂ',
    'feed': 'ਫੀਡ',
    'transaction': 'ਲੇਣ-ਦੇਣ',
    'avg_milk': 'ਔਸਤ ਦੁੱਧ',
    'dry_cows': 'ਸੂਕੀ ਗਾਏ',
    'rf_id':"ਆਰਐਫ ਆਈਡੀ",
    'breed':'ਨਸਲ',
    "sex": "ਲਿੰਗ",
    "new_cattle": "ਨਵੇਂ ਪਸ਼ੂ",
    "enter_the_rfid": "ਆਰਐਫਆਈਡੀ ਦਰਜ ਕਰੋ",
    "gender": "ਲਿੰਗ",
    "enter_the_age": "ਉਮਰ ਦਰਜ ਕਰੋ",
    "enter_the_weight": "ਵਜਨ ਦਰਜ ਕਰੋ",
    "source_of_cattle": "ਪਸ਼ੂਆਂ ਦਾ ਸੋਰਸ",
    "enter_the_breed": "ਨਸਲ ਦਰਜ ਕਰੋ",
    "status": "ਹਾਲਤ",
    "male": "ਨਰ",
    "female": "ਮਾਦਾ",
    "born_on_farm": "ਖੇਤ 'ਚ ਪੈਦਾ ਹੋਇਆ",
    "purchased": "ਖਰੀਦਿਆ ਗਿਆ",
    "milked": "ਦੁੱਧ ਦਿੱਤਾ",
    "heifer": "ਬਛਿਆ",
    "insemination": "ਗਰਭਾਧਾਨ",
    "abortion": "ਗਰਭਪਾਤ",
    "dry": "ਸੂਖਾ",
    "calved": "ਵਾਛ ਬਈ ਗਾਈ",
    "submit": "ਪ੍ਰਸਤੁਤ",
    "search_cattle": "ਪਸ਼ੂ ਖੋਜੋ",
    "state": "ਹਾਲਤ",
    "filter_options": "ਫਿਲਟਰ ਚੋਣਾਂ",
    "confirm_filters": "ਫਿਲਟਰ ਪੁਸ਼ਟੀ ਕਰੋ",
    "clear_filters": "ਫਿਲਟਰ ਮਿਟਾਓ",
    'vaccination':'ਟੀਕਾ ਲਗਾਉਣਾ',
    'please_wait':'ਕਿਰਪਾ ਕਰਕੇ ਰੁਕੋ ...',
    'events':'ਘਟਨਾਵਾਂ',
    'add_event':"ਘਟਨਾਵਾਂ ਸ਼ਾਮਲ ਕਰੋ",
    'details':"ਵੇਰਵਾ",
    'age':"ਉਮਰ",
    "weight":"ਭਾਰ",
    "milk_records":"ਦੁੱਧ ਦਾ ਰਿਕਾਰਡ",
    "date":"ਤਾਰੀਖ਼",
    "total_milk":"ਕੁੱਲ ਦੁੱਧ:",
    "litre":"ਲੀ.",
    "add_milk_data":"ਦੁੱਧ ਦਾ ਡਾਟਾ ਸ਼ਾਮਲ ਕਰੋ",
    "select_rfid":" ਆਰਐਫ ਆਈਡੀ ਚੁਣੋ",
    "morning_milk":"ਸਵੇਰ ਦਾ ਦੁੱਧ",
    "evening_milk":"ਸ਼ਾਮ ਦਾ ਦੁੱਧ",
    "milking_date":"ਦੁੱਧ ਨਿਕਾਲਣ ਦੀ ਮਿਤੀ",
    "add":" ਸ਼ਾਮਲ ਕਰੋ",
    "please_select_rfid":" ਕਿਰਪਾ ਕਰਕੇ ਆਰਐਫ ਆਈਡੀ ਚੁਣੋ",
    "morning":"ਸਵੇਰ",
    "evening":"ਸ਼ਾਮ",
    "total":"ਕੁੱਲ",
    "milk_sale":"ਦੁੱਧ ਵੇਚਣ",
    "cattle_sale":"ਪਸੂ ਵੇਚਣ",
    "other":"ਹੋਰ",
    "income":"ਆਮਦਨ",
    "expenses":"ਖਰਚ",
    'transactions':"ਲੇਨ-ਦੇਨ",
    "amount":"ਰਕਮ",
    "on_date":" ਦਾਤ ਤੇ",
    "Feed": "ਚਾਰਾ",
    "Veterinary": "ਪਸ਼ੂ ਚਿਕਿੱਤਸਾ",
    "Labor Costs": "ਮਜ਼ਦੂਰੀ ਖਰਚ",
    "Equipment and Machinery": "ਉਪਕਰਣ ਅਤੇ ਮਸ਼ੀਨਰੀ",
    "total_transactions": "ਕੁੱਲ ਲੇਨ-ਦੇਨ",
    "date_range": "ਮਿਤੀ ਦੀ ਸੀਮਾ:",
    "total_income": "ਕੁੱਲ ਆਮਦਨ",
    "income_per_category": "ਆਮਦਨ ਦਾ ਵਰਗ",
    "total_expense": "ਕੁੱਲ ਖਰਚ",
    "expense_per_category": "ਖਰਚ ਦਾ ਵਰਗ",
    "net_profit": "ਨੇਟ ਲਾਭ",
    "net_loss":"ਨੇਟ ਨੁਕਸਾਨ",
    "Milk Sale":"ੁੱਧ ਵੇਚਣ",
    "Cattle Sale":"ਪਸੂ ਵੇਚਣ",
    "date_of_income": "ਆਮਦਨ ਦੀ ਮਿਤੀ",
    "how_much_did_you_earn": "ਤੁਸੀਂ ਕਿੰਨਾ ਕਮਾਇਆ (₹ ਵਿੱਚ)",
    "select_income_type": "ਆਮਦਨ ਦੀ ਕਿਸਮ ਚੁਣੋ",
    "enter_category": "ਵਰਗ ਦਾਖਲ ਕਰੋ",
    "new_income": "ਨਵੀਂ ਆਮਦਨ",
    "Other":"ਹੋਰ",
    "new_expense": "ਨਵਾਂ ਖਰਚ",
    "date_of_expense": "ਖਰਚ ਦੀ ਮਿਤੀ",
    "how_much_did_you_spend": "ਤੁਸੀਂ ਕਿੰਨਾ ਖਰਚ ਕੀਤਾ (₹ ਵਿੱਚ)",
    "select_expense_type": "ਖਰਚ ਦੀ ਕਿਸਮ ਚੁਣੋ",
    "edit_income": "ਆਮਦਨ ਸੰਪਾਦਿਤ ਕਰੋ",
    "edit_expense": "ਖਰਚ ਸੰਪਾਦਿਤ ਕਰੋ",
    "income_category": "ਆਮਦਨ ਕੈਟੇਗਰੀ",
    "expense_category": "ਖਰਚ ਕੈਟੇਗਰੀ",
    "transaction_date": "ਲੇਨ-ਦੇਨ ਦੀ ਮਿਤੀ",
    "enter_transaction_amount": "ਲੇਨ-ਦੇਨ ਰਕਮ ਦਾਖਲ ਕਰੋ (₹ ਵਿੱਚ)",
    "delete": "ਹਟਾਓ",
    "save": "ਸੰਭਾਲੋ",
    "expiry_date": "ਮਿਆਦ ਦੀ ਮਿਤੀ",
    "current_stock": "ਮੌਜੂਦਾ ਭੰਡਾਰ",
    "current_need": "ਮੌਜੂਦਾ ਜ਼ਰੂਰਤ",
    "add_feed_item": "ਚਾਰਾ ਆਈਟਮ ਸ਼ਾਮਲ ਕਰੋ",
    "item_name": "ਆਈਟਮ ਦਾ ਨਾਮ",
    "quantity": "ਲੋੜੀਦਾ ਮਾਤਰਾ (ਇਕਾਈ)",
    "required_quantity": "ਲੋੜੀਦਾ ਮਾਤਰਾ",
    "category": "ਸ਼੍ਰੇਣੀ",
    "edit_feed_item": "ਚਾਰਾ ਆਈਟਮ ਸੋਧੋ",
    "need": "ਲੋੜ (ਇਕਾਈ)",
    "stock": "ਸਟਾਕ (ਇਕਾਈ)",
    'Born on Farm':'ਖੇਤ ਚ ਪੈਦਾ ਹੋਇਆ',
    'Purchased':'ਖਰੀਦਿਆ ਗਿਆ',
    "new_cattle_added_successfully": "ਨਵੀਂ ਪਸ਼ੂ ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ ਹੈ",
    'Add Event':"ਘਟਨਾ ਸ਼ਾਮਲ ਕਰੋं",
    "Event Name":"ਘਟਨਾ ਦਾ ਨਾਮ",
    "Event Date":"ਘਟਨਾ ਦੀ ਮਿਤੀ",
    "Edit Details": "ਵੇਰਵਾ ਸੋਧੋ",
    "Cattle Details updated Successfully!!": "ਪਸ਼ੂ ਦੇ ਵੇਰਵੇ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਹੋਏ ਹਨ!!"

  };
}
