class LocalizationHi {
  static const Map<String, String> translations = {
    'cattles': 'पशु',
    'feed': 'चारा',
    'transaction': 'लेन-देन',
    'avg_milk': 'औसत दूध',
    'dry_cows': 'सूखी गायें',
    'rf_id':"आरएफ आईडी",
    'breed':'नस्ल',
    'sex':'लिंग',
    'new_cattle':'नये पशु',
    'enter_the_rfid':'आरएफआईडी दर्ज करें ',
    'gender':'लिंग',
    'enter_the_age':'आयु दर्ज करें',
    'enter_the_weight':'वजन दर्ज करें ',
    'source_of_cattle':'पशुओं का स्रोत',
    'enter_the_breed':'नस्ल दर्ज करें',
    'status':'स्थिति',
    'male':'नर',
    'female':'मादा',
    'born_on_farm':'खेत में जन्मा',
    'purchased':'खरीदा गया',
    'milked':'दुही',
    'heifer':'बछिया',
    'insemination':'गर्भाधान',
    'abortion':'गर्भपात ',
    'dry':'सूखी ',
    'calved':'वाछ ब्याई गाय',
    'submit':'प्रस्तुत',
    'search_cattle':'पशु खोजें',
    'state':'स्थिति',
    'filter_options':'फ़िल्टर विकल्प',
    'confirm_filters':'फ़िल्टर सत्यापित करें',
    'clear_filters':'फ़िल्टर मिटाएं',
    'vaccination':'टीकाकरण',
    'please_wait':'कृपया प्रतीक्षा करें ...',
    'events':'घटनाएं',
    "add_event":"घटनाएँ जोड़ें",
    'details':"विवरण",
    "age":"आयु",
    "weight":"वज़न",
    "milk_records":"दूध का रिकॉर्ड",
    "date":"दिनांक",
    "total_milk":"कुल दूध:",
    "litre":"लि.",
    "add_milk_data":"दूध के डेटा जोड़ें",
    "select_rfid":"आरएफआईडी का चयन करें",
    "morning_milk":"सुबह का दूध",
    "evening_milk":"शाम का दूध",
    "milking_date":" दूध निकालने की तारीख",
    "add":"जोड़ें",
    "please_select_rfid":"कृपया आरएफआईडी का चयन करें",
    "morning":"सुबह",
    "evening":"शाम",
    "total":"कुल",
    "milk_sale":"दूध बिक्री",
    "cattle_sale":"पशु बिक्री",
    "other":"अन्य",
    "income":"आय",
    "expenses":"व्यय",
    "transactions":"लेन-देन",
    "amount":"राशि",
    "on_date":"तिथि",
    "Feed": "चारा",
    "Veterinary": "पशुचिकित्सा",
    "Labor Costs": "श्रम लागत",
    "Equipment and Machinery": "उपकरण और मशीनरी",
    "total_transactions": "कुल लेन-देन",
    "date_range": "तिथि सीमा:",
    "total_income": "कुल आय",
    "income_per_category": "विभाग आय",
    "total_expense": "कुल व्यय",
    "expense_per_category": "विभाग व्यय",
    "net_profit": "नेट लाभ",
    "net_loss":"नेट हानि",
    "Milk Sale":"दूध बिक्री",
    "Cattle Sale":"पशु बिक्री",
    "date_of_income": "आय की तारीख",
    "how_much_did_you_earn": "आपने कितना कमाया (₹ में)",
    "select_income_type": "आय का प्रकार चुनें",
    "enter_category": "वर्ग दर्ज करें",
    "new_income": "नई आय",
    "Other":"अन्य",
    "new_expense": "नया व्यय",
    "date_of_expense": "व्यय की तारीख",
    "how_much_did_you_spend": "आपने कितना व्यय किया (₹ में)",
    "select_expense_type": "व्यय का प्रकार चुनें",
    "edit_income": "आय संपादित करें",
    "edit_expense": "व्यय संपादित करें",
    "income_category": "आय वर्ग",
    "expense_category": "व्यय वर्ग",
    "transaction_date": "लेन-देन की तारीख",
    "enter_transaction_amount": "लेन-देन राशि दर्ज करें (₹ में)",
    "delete": "हटाएं",
    "save": "सहेजें",
    "expiry_date": "समाप्ति तिथि",
    "current_stock": "वर्तमान भंडार",
    "current_need": "वर्तमान आवश्यकता",
    "add_feed_item": "चारा आइटम जोड़ें",
    "item_name": "आइटम का नाम",
    "quantity": "आवश्यक मात्रा (इकाई)",
    "required_quantity": "आवश्यक मात्रा",
    "category": "श्रेणी",
    "edit_feed_item": "चारा आइटम संपादित करें",
    "need": "आवश्यकता (इकाई)",
    "stock": "स्टॉक (इकाई)",
    'Born on Farm':'खेत में जन्मा',
    'Purchased':'खरीदा गया',
    "new_cattle_added_successfully": "नई पशु सफलतापूर्वक जोड़ा गया",
    'Add Event':"घटना जोड़ें",
    "Event Name":"घटना का नाम",
    "Event Date":"घटना की तारीख",
    "Edit Details": "विवरण संपादित करें",
    "Cattle Details updated Successfully!!": "पशु के विवरण को सफलतापूर्वक अपडेट किया गया!!"
  };
}
