class LocalizationEn {
  static const Map<String, String> translations = {
    'cattles': 'Cattles',
    'feed': 'Feed',
    'transaction': 'Transaction',
    'avg_milk': 'Avg Milk',
    'dry_cows': 'Dry Cows',
    'rf_id':"RF Id",
    "breed":'BREED',
    "sex":"Sex",
    'new_cattle':'New Cattle',
    'enter_the_rfid':'Enter the RFID',
    'gender':'Gender',
    'enter_the_age':'Enter the Age',
    'enter_the_weight':'Enter the Weight',
    'source_of_cattle':'Source of Cattle',
    'enter_the_breed':'Enter the breed',
    'status':'Status',
    'male':'Male',
    'female':'Female',
    'born_on_farm':'Born on Farm',
    'purchased':'Purchased',
    'milked':'Milked',
    'heifer':'Heifer',
    'insemination':'Insemination',
    'abortion':'Abortion ',
    'dry':'Dry ',
    'calved':'Calved',
    'submit':'Submit',
    'search_cattle':'Search Cattle',
    'state':'State',
    'filter_options':'Filter Options',
    'confirm_filters':'Confirm Filters',
    'clear_filters':'Clear Filters',
    'vaccination':'Vaccination',
    'please_wait':'Please wait ...',
    'events':"Events",
    'add_event':"Add Event",
    'details':"Details",
    "age":"Age",
    "weight":"Weight",
    "milk_records":"Milk Records",
    "date":"Date",
    "total_milk":"Total Milk:",
    "litre":"L",
    "add_milk_data":"Add Milk Data",
    "select_rfid":"Select RFID",
    "morning_milk":"Morning Milk",
    "evening_milk":"Evening Milk",
    "milking_date":"Milking Date",
    "add":"Add",
    "please_select_rfid":"Please select RFID",
    "morning":"Morning",
    "evening":"Evening",
    "total":"Total",
    "transactions":"Transactions",
    "milk_sale":"Milk Sale",
    "cattle_sale":"Cattle Sale",
    "other":"Other",
    "income":"Income",
    "expenses":"Expenses",
    "amount":"Amount",
    "on_date":"On Date",
    "Feed":"Feed",
    "Veterinary":"Veterinary",
    "Labor Costs":"Labor Costs",
    "Equipment and Machinery":"Equipment and Machinery",
    "total_transactions":"Total Transactions",
    "date_range":"Date range:",
    "total_income":"Total Income",
    "income_per_category":"Income per Category",
    "total_expense":"Total Expense",
    "expense_per_category":"Expense per Category",
    "net_profit":"Net Profit",
    "net_loss":"Net Loss",
    "Milk Sale":"Milk Sale",
    "Cattle Sale":"Cattle Sale",
    "date_of_income":"Date of Income",
    "how_much_did_you_earn":"How much did you earn (in ₹)",
    "select_income_type":"Select Income type",
    "enter_category":"Enter Category",
    "new_income":"New Income",
    "new_expense":"New Expense",
    "Other":"Other",
    "date_of_expense":"Date of expense",
    "how_much_did_you_spend":"How much did you spend (in ₹)",
    "select_expense_type":"Select Expense type",
    "edit_income": "Edit Income",
    "edit_expense": "Edit Expense",
    "income_category": "Income Category",
    "expense_category": "Expense Category",
    "transaction_date": "Transaction Date",
    "enter_transaction_amount": "Enter Transaction Amount (in ₹)",
    "delete":"Delete",
    "save":"Save",
    "expiry_date": "Expiry Date",
    "current_stock": "Current Stock",
    "current_need": "Current Need",
    "add_feed_item": "Add Feed Item",
    "item_name": "Item Name",
    "quantity": "Required Quantity (unit)",
    "required_quantity": "Required Quantity",
    "category": "Category",
    "edit_feed_item":"Edit Feed Item",
    "need":"Need (unit)",
    "stock":"Stock (unit)",
    'Born on Farm':'Born on Farm',
    'Purchased':'Purchased',
    'new_cattle_added_successfully':"New Cattle Added Successfully!!",
    'Add Event':"Add Event",
    "Event Name":"Event Name",
    "Event Date":"Event date",
    "Edit Details":"Edit Details",
    "Cattle Details updated Successfully!!": "Cattle Details updated Successfully!!"
  };
}
